Added Navigation component
pubnub/chat-components-android-examples pull request #23
Opened 2022-12-08 11:04 UTC by mateusz-cichosz

2022-12-09 12:17 UTC, Chesteer89 requested changes

2022-12-09 12:17 UTC, Chesteer89 commented on buildSrc/src/main/java/com/pubnub/components/buildsrc/Dependencies.kt
> +        const val navigation = "androidx.navigation:navigation-compose:2.4.0-beta07"
Why we're using beta? We agreed to use stable dependencies.

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/extensions/Bundle.kt
> +inline fun <reified T : Parcelable> Bundle.parcelable(key: String): T? = when {
Is it still needed? Shouldn't we store the currently logged user somewhere instead of passing it to activity?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/MainActivity.kt
> +                    NavGraph(navController = navController)
The code is not readable, it suggested just a navigation graph without any views.

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +        startDestination = Screens.Login.route)
Code format

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                    navController.navigate("${Screens.Channel.route}/$json")
Shouldn't we use one instance of Gson? Creating a new one each time is a waste of memory. 
Additionally, why we're passing the JSON to the route? Did you followed https://developer.android.com/jetpack/compose/navigation#nav-with-args ?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +        composable(
Please check how navigation works in [Compose samples](https://github.com/android/compose-samples) - JetChat, Rally and Reply.

For better understanding please check some posts on Medium like https://medium.com/google-developer-experts/modular-navigation-with-jetpack-compose-fda9f6b2bef7

And finish the navigation code labs - https://developer.android.com/codelabs/jetpack-compose-navigation

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                    navController.navigate("${Screens.Channel.route}/$json")
Ignore the GSON, this route is so bad... Please just follow guides on how to create a clean route. We can even create a helper to create it like `Screen.Channel.Route(channelId, userId)`

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +            val userParameters =
Do we need to store user parameters like that? Is there a better solution? Like storing the current user in persisted storage (db or shared prefs?) to log in automatically / or logout

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                initializePubNub(userParameters.userId)
Shouldn't we initialize PubNub and parameters right after successful login?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                                val json = Uri.encode(Gson().toJson(chatParameters))
Again, this route with Url encoded json is awful

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +            val chatParameters =
Shouldn't we pass chat parameters into the route directly?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +private fun initializePubNub(userId: String) {
This one can be `by lazy` declared in the Application. Just make sure you're not calling it before you set `userId`

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavType.kt
> +class ChatParametersType : NavType<ChatParameters>(isNullableAllowed = false) {
I believe it should be removed. Do we really need parcelable when we can pass arguments to the route?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/Screens.kt
> +            navArgument(userParametersArg) { type = UserParametersType() }
Why it's wrapped into parcelable? Isn't it easier to create multiple arguments?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/ui/view/Channel.kt
> +                        secondUserId = it.description ?: "",
Do we really need to pass user ids to callback? Shouldn't it be obtained from Channel data?

2022-12-09 12:17 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/ui/view/Login.kt
> +                UserParameters(userId = it.id,
What is the type here?

2022-12-12 06:15 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                AppTheme(pubNub = ChatApplication.pubNub) {
Initialization of `AppTheme` should be done once as a root of `NavHost`. We need to mark `pubNub` as a nullable parameter, and check it inside (if null -> RepositoryProvider else ChatProvider). Otherwise, with every change between the channel and chat screen, the PN will be initialized -> new subscribe will be called.

2022-12-12 06:30 UTC, Chesteer89 commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +        startDestination = Screens.Login.route)
To consider: Do we want to start with the Login Screen?

I understand that it's just a sample, but the correct behavior should be to move to the channel list.
See:
https://www.ittybittyapps.com/blog/2022-10-19-navigation-compose/
https://developer.android.com/guide/navigation/navigation-conditional

2023-01-10 10:37 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                AppTheme(pubNub = ChatApplication.pubNub) {
Done

2023-01-10 10:38 UTC, mateusz-cichosz commented on buildSrc/src/main/java/com/pubnub/components/buildsrc/Dependencies.kt
> +        const val navigation = "androidx.navigation:navigation-compose:2.4.0-beta07"
Changed back

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/extensions/Bundle.kt
> +inline fun <reified T : Parcelable> Bundle.parcelable(key: String): T? = when {
Deleted

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/MainActivity.kt
> +                    NavGraph(navController = navController)
Changed

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +        startDestination = Screens.Login.route)
Changed

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                    navController.navigate("${Screens.Channel.route}/$json")
Removed Gson and passing through Json

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                initializePubNub(userParameters.userId)
Done

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavGraph.kt
> +                                val json = Uri.encode(Gson().toJson(chatParameters))
Removed

2023-01-10 10:38 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/navigation/NavType.kt
> +class ChatParametersType : NavType<ChatParameters>(isNullableAllowed = false) {
Removed

2023-01-10 10:39 UTC, mateusz-cichosz commented on telehealth-example/src/main/java/com/pubnub/components/example/telehealth/ui/view/Login.kt
> +                UserParameters(userId = it.id,
User type, doctor or patient

2023-01-11 14:21 UTC, Chesteer89 approved these changes

2023-01-11 14:25 UTC, merged